export const SEARCH_USER_INIT = 'SEARCH_USER_INIT';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILED = 'SEARCH_USER_FAILED';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
